#!/bin/bash
echo "=== Test des filtres Nurturing ==="
echo ""
echo "1. Test export interactions CSV (sans filtres)"
echo "GET /api/nurturing/interactions/export?prospect_id=test&format=csv"
echo ""
echo "2. Test export interactions CSV (avec filtres types)"
echo "GET /api/nurturing/interactions/export?prospect_id=test&format=csv&types=appel,email"
echo ""
echo "3. Test export interactions CSV (avec date range)"
echo "GET /api/nurturing/interactions/export?prospect_id=test&format=csv&start_date=2024-01-01&end_date=2024-12-31"
echo ""
echo "4. Test KPIs (sans filtre)"
echo "GET /api/nurturing/kpis"
echo ""
echo "5. Test KPIs (avec date range)"
echo "GET /api/nurturing/kpis?start_date=2024-01-01&end_date=2024-12-31"
echo ""
echo "Tests prêts à être exécutés manuellement dans le navigateur"
